# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpparma_hello_world <- function() {
    .Call(`_TraitGMYC_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_TraitGMYC_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_TraitGMYC_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_TraitGMYC_rcpparma_bothproducts`, x)
}

mvrnormArma <- function(n, mu, sigma) {
    .Call(`_TraitGMYC_mvrnormArma`, n, mu, sigma)
}

colMeansArma <- function(x) {
    .Call(`_TraitGMYC_colMeansArma`, x)
}

meansAfterMvrnormDraw <- function(n, mu, sigma) {
    .Call(`_TraitGMYC_meansAfterMvrnormDraw`, n, mu, sigma)
}

getMvrnormMeansAfterTime <- function(tt, n, mu, sigma) {
    .Call(`_TraitGMYC_getMvrnormMeansAfterTime`, tt, n, mu, sigma)
}

notWorking <- function(tt, n, mu, sigma) {
    .Call(`_TraitGMYC_notWorking`, tt, n, mu, sigma)
}

